export type SecteurDetail = {
  slug: string;
  population: number;
  superficie: number;
  cp: string;
  intercommunalite: string;
  altitude?: string;
  ceQuiDifferencie: string[];
  ecoles: { nom: string; type: "Maternelle" | "Primaire" | "Collège" | "Lycée" | "Supérieur" | "Privé"; precision?: string }[];
  restaurants: { nom: string; cuisine: string; gamme: "Bistrot" | "Gastro" | "Étoilé" | "Pizza" | "Brasserie" | "Café" }[];
  associations: { nom: string; activite: string }[];
  quartiers: { nom: string; description: string; prixIndicatif?: string }[];
  evolutionPrix: { annee: number; prixM2: number }[];
  videoInsta?: { titre: string; duree: string; thumb?: string };
  galerie?: string[];
};

export const secteursDetails: Record<string, SecteurDetail> = {
  "saint-didier-au-mont-dor": {
    slug: "saint-didier-au-mont-dor",
    population: 7435,
    superficie: 7.7,
    cp: "69370",
    intercommunalite: "Métropole de Lyon",
    altitude: "260 — 547 m",
    ceQuiDifferencie: [
      "Une des communes les plus convoitées de la Métropole — demande structurellement supérieure à l'offre",
      "Tissu associatif et scolaire de référence régionale",
      "Cadre village conservé à 15 minutes du centre de Lyon",
      "Forte présence de cadres dirigeants et de professions libérales",
    ],
    ecoles: [
      { nom: "École publique du Bourg", type: "Primaire", precision: "Maternelle + élémentaire publique, centre village" },
      { nom: "École publique de Saint-Fortunat", type: "Primaire", precision: "Maternelle + élémentaire publique" },
      { nom: "Ensemble scolaire Fromente-Saint-François", type: "Privé", precision: "Maternelle au collège, sous contrat — la seule école privée sur la commune" },
      { nom: "Collège Jean-Philippe Rameau", type: "Collège", precision: "Public, à Champagne-au-Mont-d'Or — collège de secteur (~6 min)" },
      { nom: "Lycées lyonnais & Écully", type: "Lycée", precision: "Selon orientation : Cevert, La Martinière Duchère, lycées internationaux (10-15 min)" },
    ],
    restaurants: [
      { nom: "L'Éclat de Pierre", cuisine: "Bistronomie avec terrasse · 4,6★ (388 avis)", gamme: "Gastro" },
      { nom: "Aux Montagnards", cuisine: "Cuisine française traditionnelle / fondue · 4,2★ (1 533 avis)", gamme: "Brasserie" },
      { nom: "La Cantine du Village", cuisine: "Bistrot lyonnais · 4,4★ (283 avis)", gamme: "Bistrot" },
      { nom: "La Boîte Noire", cuisine: "Pizzeria de référence · 4,7★", gamme: "Pizza" },
      { nom: "Comptoir Fortunella", cuisine: "Table sarde familiale · 4,9★", gamme: "Bistrot" },
      { nom: "Les Jardins de Saint-Didier", cuisine: "Pizza & cuisine, terrasse pétanque · 4,5★", gamme: "Pizza" },
    ],
    associations: [
      { nom: "FCLDSD — Football Club Limonest-Dardilly-Saint-Didier", activite: "Club mutualisé évoluant en National 3" },
      { nom: "HBCCD — Handball Club Saint-Cyr / Saint-Didier", activite: "Handball, gymnase de Saint-Didier" },
      { nom: "Boule des Monts d'Or", activite: "Sport boules lyonnaises" },
      { nom: "AGYD — Activités Gymniques de Saint-Didier", activite: "Gymnastique et yoga toutes générations" },
      { nom: "Aïkido / Judo Ouest Grand Lyon", activite: "Arts martiaux" },
      { nom: "Badmin d'Or", activite: "Badminton" },
      { nom: "Comité d'animation de Saint-Didier", activite: "Événements villageois, marché, fête de la Saint-Jean" },
    ],
    quartiers: [
      { nom: "Centre village", description: "Le cœur historique : place de la mairie, commerces de bouche, ruelles en pierres dorées. Très recherché pour son cachet.", prixIndicatif: "7 000 — 8 500 €/m²" },
      { nom: "Saint-Fortunat", description: "Hameau préservé, ambiance plus rurale, vues dégagées sur les coteaux.", prixIndicatif: "6 800 — 8 000 €/m²" },
      { nom: "Plat de l'Air", description: "Vastes propriétés sur les hauteurs, sous-bois, calme absolu — l'adresse historique des familles établies.", prixIndicatif: "7 500 — 9 000 €/m²" },
      { nom: "Les Carrières / Le Tourillon", description: "Mix maisons familiales rénovées et constructions contemporaines, proche du collège.", prixIndicatif: "6 200 — 7 800 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 5800 }, { annee: 2021, prixM2: 6300 }, { annee: 2022, prixM2: 6600 },
      { annee: 2023, prixM2: 6700 }, { annee: 2024, prixM2: 6750 }, { annee: 2025, prixM2: 6800 },
    ],
    videoInsta: { titre: "Saint-Didier vu d'en haut — visite du Mont Cindre", duree: "2:10" },
    galerie: ["/photos/secteurs/saint-didier-1.jpg", "/photos/secteurs/saint-didier-2.jpg", "/photos/secteurs/saint-didier-3.jpg", "/photos/secteurs/saint-didier-4.jpg", "/photos/secteurs/saint-didier-5.jpg", "/photos/secteurs/saint-didier-6.jpg"],
  },
  "saint-cyr-au-mont-dor": {
    slug: "saint-cyr-au-mont-dor",
    population: 6327,
    superficie: 7.29,
    cp: "69450",
    intercommunalite: "Métropole de Lyon",
    altitude: "180 — 450 m",
    ceQuiDifferencie: [
      "Adresse parmi les plus prestigieuses de la Métropole, vues panoramiques sur la Saône",
      "Concentration exceptionnelle de bastides classées et de propriétés d'exception",
      "Marché off-market dominant — beaucoup de transactions sans publication publique",
      "Patrimoine bâti en pierres dorées remarquable",
    ],
    ecoles: [
      { nom: "École publique de Saint-Cyr (groupe scolaire centre)", type: "Primaire", precision: "Maternelle + élémentaire publique" },
      { nom: "Sainte-Marie Lyon — campus Saint-Cyr", type: "Privé", precision: "Établissement réputé de l'Ouest lyonnais — primaire & secondaire" },
      { nom: "Collège Jean-Philippe Rameau", type: "Collège", precision: "Public, à Champagne-au-Mont-d'Or — collège de secteur (~6 min)" },
      { nom: "Collège & lycée Sainte-Marie Lyon", type: "Privé", precision: "Section collège-lycée du campus Sainte-Marie sur Saint-Cyr" },
    ],
    restaurants: [
      { nom: "L'Ermitage Cuisine à Manger", cuisine: "Bistronomie avec vue Lyon · 4,5★ (640 avis)", gamme: "Gastro" },
      { nom: "Le Comptoir de St Cyr", cuisine: "Brasserie · 4,3★ (1 188 avis), 17 rte de Lyon", gamme: "Brasserie" },
      { nom: "Là-Haut sur la Colline", cuisine: "Cuisine française · 4,3★ (1 183 avis), rte du Mont-Cindre", gamme: "Bistrot" },
      { nom: "Brasserie des Monts d'Or", cuisine: "Française · 3,9★ (905 avis), pl. de la République", gamme: "Brasserie" },
    ],
    associations: [
      { nom: "Saint-Cyr Tennis", activite: "Club de tennis, courts couverts" },
      { nom: "Patrimoine de Saint-Cyr", activite: "Préservation des bastides et du bâti ancien" },
      { nom: "HBCCD — Handball Saint-Cyr / Saint-Didier", activite: "Handball intercommunal, gymnase de Saint-Didier" },
    ],
    quartiers: [
      { nom: "Le Bourg", description: "Cœur historique avec la mairie, l'église et les commerces. Bastides du XVIIIᵉ.", prixIndicatif: "7 200 — 8 800 €/m²" },
      { nom: "Les Verrières", description: "Quartier d'exception sur les hauteurs, propriétés avec parcs.", prixIndicatif: "8 500 — 11 000 €/m²" },
      { nom: "Combe Blanche", description: "Versant sud, vues magnifiques, propriétés isolées dans la végétation.", prixIndicatif: "7 800 — 9 500 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 6100 }, { annee: 2021, prixM2: 6700 }, { annee: 2022, prixM2: 7000 },
      { annee: 2023, prixM2: 7100 }, { annee: 2024, prixM2: 7150 }, { annee: 2025, prixM2: 7200 },
    ],
    videoInsta: { titre: "Bastide en pierres dorées — visite exclusive", duree: "1:45" },
    galerie: ["/photos/secteurs/saint-cyr-1.jpg", "/photos/secteurs/saint-cyr-2.jpg", "/photos/secteurs/saint-cyr-3.jpg", "/photos/secteurs/saint-cyr-4.jpg", "/photos/secteurs/saint-cyr-5.jpg", "/photos/secteurs/saint-cyr-6.jpg"],
  },
  "ecully": {
    slug: "ecully",
    population: 17944,
    superficie: 8.0,
    cp: "69130",
    intercommunalite: "Métropole de Lyon",
    altitude: "190 — 320 m",
    ceQuiDifferencie: [
      "Pôle universitaire d'excellence : EM Lyon Business School, Centrale Lyon, Institut Paul Bocuse, ECAM",
      "Connexions Lyon centre : ligne 3 du métro à venir, autoroute A6 à 5 min",
      "Parc du Vallon (40 ha) — poumon vert de la commune",
      "Mix résidentiel : grandes propriétés historiques + résidences neuves de standing",
    ],
    ecoles: [
      { nom: "Collège Laurent Mourguet", type: "Collège", precision: "Public, 3 bis rue Jean Rigaud" },
      { nom: "Collège Sacré-Cœur — Don Bosco Écully", type: "Privé", precision: "47 av. du Dr Terver — établissement notable de la commune" },
      { nom: "École Saint-Joseph", type: "Privé", precision: "Maternelle + primaire" },
      { nom: "EM Lyon Business School", type: "Supérieur" },
      { nom: "École Centrale de Lyon", type: "Supérieur" },
      { nom: "ECAM Lyon", type: "Supérieur" },
      { nom: "Institut Paul Bocuse", type: "Supérieur", precision: "Hôtellerie-restauration de référence mondiale" },
    ],
    restaurants: [
      { nom: "Saisons (Institut Paul Bocuse)", cuisine: "Gastronomie d'application étoilée Michelin · 4,8★ (514 avis)", gamme: "Étoilé" },
      { nom: "Au Bel Avenir", cuisine: "Brasserie ouest lyonnais · 4,7★ (207 avis), 12 all. des Tullistes", gamme: "Brasserie" },
      { nom: "Au Comptoir d'Écully", cuisine: "Bistrot · 4,9★ (87 avis)", gamme: "Bistrot" },
      { nom: "Volfoni Écully", cuisine: "Italien · 4,6★ (279 avis), chem. Jean-Marie Vianney", gamme: "Bistrot" },
      { nom: "Restaurant Le Village", cuisine: "Bistrot / burger · 4,5★ (332 avis), av. du Dr Terver", gamme: "Bistrot" },
      { nom: "L'Entre-Nous", cuisine: "Italien · 4,5★ (617 avis), all. Moulin Berger", gamme: "Bistrot" },
      { nom: "Kif Angkor", cuisine: "Cambodgien · 5★ (44 avis), rue Marietton", gamme: "Bistrot" },
      { nom: "Pâtisserie Sève (Richard Sève)", cuisine: "Pâtisserie haute couture, CC Écully Grand Ouest", gamme: "Café" },
    ],
    associations: [
      { nom: "Écully Sports", activite: "Multisports : tennis, basket, judo, gymnastique" },
      { nom: "Écully Athlétisme", activite: "Athlétisme amateur et compétition" },
      { nom: "MJC d'Écully", activite: "Activités culturelles, théâtre, musique" },
      { nom: "Comité de jumelage Écully — Lourinhã (Portugal)", activite: "Échanges internationaux" },
    ],
    quartiers: [
      { nom: "Le Centre", description: "Centre-ville commerçant, mairie, marché du dimanche, résidences anciennes rénovées.", prixIndicatif: "5 500 — 6 500 €/m²" },
      { nom: "Pérollier", description: "Quartier familial avec écoles, parc, résidences récentes.", prixIndicatif: "5 200 — 6 000 €/m²" },
      { nom: "Valvert", description: "Hauteurs résidentielles, grandes maisons, calme.", prixIndicatif: "6 200 — 7 500 €/m²" },
      { nom: "Le Coulouvrier", description: "Mix maisons individuelles + petits collectifs, proche EM Lyon.", prixIndicatif: "5 500 — 6 200 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 5100 }, { annee: 2021, prixM2: 5500 }, { annee: 2022, prixM2: 5800 },
      { annee: 2023, prixM2: 5850 }, { annee: 2024, prixM2: 5870 }, { annee: 2025, prixM2: 5900 },
    ],
    videoInsta: { titre: "Pourquoi Écully attire les familles cadres", duree: "1:30" },
    galerie: ["/photos/secteurs/ecully-1.jpg", "/photos/secteurs/ecully-2.jpg", "/photos/secteurs/ecully-3.jpg", "/photos/secteurs/ecully-4.jpg", "/photos/secteurs/ecully-5.jpg", "/photos/secteurs/ecully-6.jpg"],
  },
  "dardilly": {
    slug: "dardilly",
    population: 9221,
    superficie: 13.99,
    cp: "69570",
    intercommunalite: "Métropole de Lyon",
    altitude: "200 — 420 m",
    ceQuiDifferencie: [
      "Très grandes parcelles disponibles — moyenne de 1 200 m² de terrain par maison",
      "Accès direct A6 vers Paris, sortie immédiate Limonest / Dardilly",
      "Deux lycées de référence sur la commune : Lycée Hôtelier François Rabelais et Lycée Horticole Lyon-Dardilly",
      "Parcours de golf Bluegreen Porte de Lyon, espaces naturels protégés",
    ],
    ecoles: [
      { nom: "École des Noyeraies", type: "Primaire", precision: "Publique, 7 chem. des Écoliers" },
      { nom: "Groupe scolaire Le Grégoire", type: "Primaire", precision: "Maternelle + primaire publique, 42 chem. de Parsonge" },
      { nom: "École Saint-Joseph", type: "Privé", precision: "Mixte, 9 rue du Curé d'Ars" },
      { nom: "Pas de collège public à Dardilly", type: "Collège", precision: "Secteur public : Collège Jean-Philippe Rameau (Champagne, ~5 min) ou Victor Schœlcher (Lyon 9)" },
      { nom: "Collège Aux Lazaristes La Salle — site Limonest", type: "Privé", precision: "Limitrophe Dardilly à 5 min · 392 chem. de la Sablière" },
      { nom: "Lycée François Rabelais & GRETA-CFA Hôtelier", type: "Lycée", precision: "Lycée hôtelier réputé avec restaurant d'application Saint-Jean — 4 chem. du Dodin" },
      { nom: "Lycée Horticole, Paysage et Environnement Lyon-Dardilly", type: "Lycée", precision: "Lycée agricole, 26 chem. de la Bruyère" },
      { nom: "Maison Petite Enfance Dardy'gones", type: "Maternelle", precision: "Crèche / petite enfance, 54 all. du Levant" },
    ],
    restaurants: [
      { nom: "Restaurant Bol d'Air", cuisine: "Gastro / bistrot · 4,7★ (2 425 avis), 77 av. de Verdun", gamme: "Gastro" },
      { nom: "Odyssée Restaurant", cuisine: "Bistrot soigné · 4,9★ (153 avis), chem. de la Bruyère", gamme: "Bistrot" },
      { nom: "L'Auberge du Village", cuisine: "Française traditionnelle · 4,5★ (684 avis), pl. de l'Église", gamme: "Brasserie" },
      { nom: "Restaurant Comme Avant", cuisine: "Bistronomie · 4,8★ (87 avis), pl. de l'Église", gamme: "Bistrot" },
      { nom: "La Table du Bas", cuisine: "Cuisine française · 4,9★ (115 avis), av. de Verdun", gamme: "Bistrot" },
      { nom: "Le Patio Dardilly", cuisine: "Européen / français · 4,2★ (434 avis)", gamme: "Brasserie" },
      { nom: "Café Marcel", cuisine: "Café / végétarien · 5★ (86 avis), av. de Verdun", gamme: "Café" },
      { nom: "Double 7 Dardilly", cuisine: "Cuisine moderne · 4,5★ (353 avis), chem. des Peupliers", gamme: "Bistrot" },
    ],
    associations: [
      { nom: "FCLDSD — Football Club Limonest-Dardilly-Saint-Didier", activite: "Club mutualisé évoluant en National 3" },
      { nom: "Tennis Club de Dardilly", activite: "Tennis, courts couverts" },
      { nom: "Golf Bluegreen Porte de Lyon", activite: "Parcours 9 et 18 trous, école de golf" },
    ],
    quartiers: [
      { nom: "Le Paillet", description: "Quartier résidentiel calme, proche centre, écoles à pied.", prixIndicatif: "4 800 — 5 500 €/m²" },
      { nom: "La Beffe", description: "Hauteurs, grandes maisons, vues dégagées sur la Saône.", prixIndicatif: "5 500 — 6 500 €/m²" },
      { nom: "Porte de Lyon", description: "Proximité commerciale (centre Carrefour), petites maisons et collectifs.", prixIndicatif: "4 500 — 5 200 €/m²" },
      { nom: "Les Noyeraies", description: "Quartier pavillonnaire, calme, proche parcours de golf.", prixIndicatif: "5 200 — 6 000 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 4500 }, { annee: 2021, prixM2: 4900 }, { annee: 2022, prixM2: 5100 },
      { annee: 2023, prixM2: 5150 }, { annee: 2024, prixM2: 5180 }, { annee: 2025, prixM2: 5200 },
    ],
    videoInsta: { titre: "Pourquoi Dardilly est sous-coté", duree: "1:15" },
    galerie: ["/photos/secteurs/dardilly-1.jpg", "/photos/secteurs/dardilly-2.jpg", "/photos/secteurs/dardilly-3.jpg", "/photos/secteurs/dardilly-4.jpg", "/photos/secteurs/dardilly-5.jpg", "/photos/secteurs/dardilly-6.jpg"],
  },
  "limonest": {
    slug: "limonest",
    population: 4012,
    superficie: 7.6,
    cp: "69760",
    intercommunalite: "Métropole de Lyon",
    altitude: "270 — 625 m",
    ceQuiDifferencie: [
      "Patrimoine en pierres dorées exceptionnel (50+ bastides classées ou inventoriées)",
      "Mont Verdun (le point culminant du Mont d'Or) — vues à 360°",
      "Une des communes les plus boisées de la Métropole",
      "Pôle économique tertiaire (Techlid) côtoyant un cadre village préservé",
    ],
    ecoles: [
      { nom: "École publique de Limonest", type: "Primaire", precision: "Maternelle + élémentaire publique" },
      { nom: "Collège Aux Lazaristes La Salle — site Limonest", type: "Privé", precision: "392 chem. de la Sablière — collège privé sous contrat, très demandé" },
      { nom: "Lycée Saint-Just (Lyon 5)", type: "Lycée", precision: "Lycée public, ~12 min" },
      { nom: "Lycées internationaux & ECAM (Lyon)", type: "Lycée", precision: "Accès rapide via les axes A6 / Lyon Ouest" },
    ],
    restaurants: [
      { nom: "La Pièce du Boucher", cuisine: "Viandes premium · 4,6★ (1 356 avis), av. Général de Gaulle", gamme: "Gastro" },
      { nom: "Jols Lyon Limonest", cuisine: "Poissons & fruits de mer · 4,3★ (1 748 avis)", gamme: "Brasserie" },
      { nom: "La Casa Nostra", cuisine: "Italien / pizza · 4,3★ (801 avis), pl. Decurel", gamme: "Pizza" },
      { nom: "Restaurant Côté Balcon", cuisine: "Bistrot avec vue · 4,6★ (240 avis), pl. du Griffon", gamme: "Bistrot" },
      { nom: "Maison Savoure", cuisine: "Française · 4,6★ (354 avis), Parc Swen", gamme: "Gastro" },
      { nom: "ILO", cuisine: "Restaurant / cantine / bar · 4,9★, all. des Frênes", gamme: "Bistrot" },
      { nom: "Les Halles de Limonest", cuisine: "Concept halles · 4,3★ (198 avis)", gamme: "Brasserie" },
      { nom: "MIDI SEIZE", cuisine: "Cuisine soignée · 5★ (98 avis), chem. de Champivost", gamme: "Bistrot" },
    ],
    associations: [
      { nom: "Limonest Tennis", activite: "Tennis club avec école" },
      { nom: "Pierres Dorées en Mont d'Or", activite: "Préservation du patrimoine bâti" },
      { nom: "FCLDSD — Football Club Limonest-Dardilly-Saint-Didier", activite: "Club mutualisé évoluant en National 3" },
    ],
    quartiers: [
      { nom: "Le Bourg", description: "Centre village avec église, mairie, commerces de proximité.", prixIndicatif: "5 200 — 6 200 €/m²" },
      { nom: "Les Grillons", description: "Lotissement résidentiel des années 80, maisons familiales.", prixIndicatif: "5 000 — 5 800 €/m²" },
      { nom: "Sans Souci", description: "Hauteurs, grandes propriétés en pierres dorées, calme absolu.", prixIndicatif: "6 500 — 8 500 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 4800 }, { annee: 2021, prixM2: 5200 }, { annee: 2022, prixM2: 5450 },
      { annee: 2023, prixM2: 5530 }, { annee: 2024, prixM2: 5570 }, { annee: 2025, prixM2: 5600 },
    ],
    videoInsta: { titre: "Sur les pas du Mont Verdun — patrimoine de Limonest", duree: "2:00" },
    galerie: ["/photos/secteurs/limonest-1.jpg", "/photos/secteurs/limonest-2.jpg", "/photos/secteurs/limonest-3.jpg", "/photos/secteurs/limonest-4.jpg", "/photos/secteurs/limonest-5.jpg", "/photos/secteurs/limonest-6.jpg"],
  },
  "champagne-au-mont-dor": {
    slug: "champagne-au-mont-dor",
    population: 6311,
    superficie: 2.6,
    cp: "69410",
    intercommunalite: "Métropole de Lyon",
    altitude: "190 — 280 m",
    ceQuiDifferencie: [
      "Petite commune à taille humaine — la plus dense du Mont d'Or",
      "Centre village animé avec marché hebdomadaire et commerces de proximité",
      "Très bonne connexion bus vers Lyon via TCL (lignes 4 et 19)",
      "Une des seules communes du Mont d'Or avec un collège public sur son territoire",
    ],
    ecoles: [
      { nom: "Groupe scolaire public du Centre", type: "Primaire", precision: "6 classes maternelle + 12 classes élémentaire" },
      { nom: "École Les Chartreux Saint-Joseph", type: "Privé", precision: "Maternelle + primaire, sous contrat" },
      { nom: "Collège Jean-Philippe Rameau", type: "Collège", precision: "Public, 646 élèves — collège de secteur du Mont d'Or" },
      { nom: "Lycée Jean Perrin (Lyon 9) ou La Martinière Duchère", type: "Lycée", precision: "Lycées publics les plus proches" },
    ],
    restaurants: [
      { nom: "O Platanes", cuisine: "Française · 4,6★ (603 avis), av. de Lanessan", gamme: "Bistrot" },
      { nom: "N'Autre MOnde", cuisine: "Asiatique · 4,7★ (254 avis), av. de Montlouis", gamme: "Bistrot" },
      { nom: "Le Rouge-Gorge", cuisine: "Française · 4,3★ (343 avis), pl. Ludovic Monnier", gamme: "Bistrot" },
      { nom: "Le Rictoria", cuisine: "Française / américaine · 4,6★ (243 avis), chem. du Tronchon", gamme: "Brasserie" },
      { nom: "Da Cocó by La Boîte Noire", cuisine: "Italien / pizza · 4,7★ (197 avis), av. de Lanessan", gamme: "Pizza" },
      { nom: "Ninkasi Champagne", cuisine: "Burgers / brewpub · 4,4★ (668 avis)", gamme: "Brasserie" },
      { nom: "La Ferme des Monts d'Or", cuisine: "Française · 4,5★ (358 avis), av. de Lanessan", gamme: "Bistrot" },
    ],
    associations: [
      { nom: "Champagne Football", activite: "Foot jeunes et adultes" },
      { nom: "Tennis de Champagne", activite: "Club avec courts" },
      { nom: "Comité des fêtes", activite: "Marché de Noël, fête du village" },
    ],
    quartiers: [
      { nom: "Centre", description: "Cœur de village, commerces, mairie, église, marché.", prixIndicatif: "5 400 — 6 200 €/m²" },
      { nom: "Les Bruyères", description: "Quartier pavillonnaire des années 70-80, calme, accès rapide aux écoles.", prixIndicatif: "5 200 — 5 800 €/m²" },
      { nom: "Le Rocher", description: "Hauteurs, vues, résidences plus récentes.", prixIndicatif: "5 800 — 6 500 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 4800 }, { annee: 2021, prixM2: 5200 }, { annee: 2022, prixM2: 5500 },
      { annee: 2023, prixM2: 5650 }, { annee: 2024, prixM2: 5740 }, { annee: 2025, prixM2: 5800 },
    ],
    videoInsta: { titre: "Champagne — la commune la plus dynamique du Mont d'Or", duree: "1:25" },
    galerie: ["/photos/secteurs/champagne-1.jpg", "/photos/secteurs/champagne-2.jpg", "/photos/secteurs/champagne-3.jpg", "/photos/secteurs/champagne-4.jpg", "/photos/secteurs/champagne-5.jpg", "/photos/secteurs/champagne-6.jpg"],
  },
  "saint-just-saint-rambert": {
    slug: "saint-just-saint-rambert",
    population: 15764,
    superficie: 40,
    cp: "42170",
    intercommunalite: "Loire Forez Agglomération",
    altitude: "385 — 510 m",
    ceQuiDifferencie: [
      "Ville à taille humaine entre Lyon (50 min) et Saint-Étienne (15 min)",
      "Bords de Loire aménagés sur 6 km — attraction touristique majeure",
      "Marché immobilier 2x à 3x moins cher que la Métropole de Lyon",
      "Excellent rendement locatif (5 — 6%) — paradis des investisseurs",
    ],
    ecoles: [
      { nom: "Écoles publiques Saint-Just & Saint-Rambert", type: "Primaire", precision: "Plusieurs groupes scolaires publics répartis sur les deux centres" },
      { nom: "École privée Saint-Joseph", type: "Privé" },
      { nom: "Collège public Anne Frank", type: "Collège", precision: "897 élèves, section sport — récemment rénové (14 M€), un des plus gros de la Loire" },
      { nom: "Collège privé Saint-Joseph", type: "Privé" },
      { nom: "Lycée polyvalent François Mauriac (Andrézieux-Bouthéon)", type: "Lycée", precision: "~8 min" },
    ],
    restaurants: [
      { nom: "Le Minimaliste", cuisine: "Restaurant tendance, planches & cocktails · 4,9★ (203 avis), av. du Stade", gamme: "Bistrot" },
      { nom: "Les Serres Babylone", cuisine: "Fleuriste-restaurant-bar · 4,6★ (337 avis), av. des Barques", gamme: "Bistrot" },
      { nom: "Ô Benestar", cuisine: "Cuisine sud-ouest · 4,5★ (317 avis), pl. du Pont", gamme: "Bistrot" },
      { nom: "Les Remparts de Saint-Rambert", cuisine: "Française dans bâti historique · 4,2★ (121 avis), rue de la Loire", gamme: "Brasserie" },
      { nom: "Brasserie de l'Industrie", cuisine: "Française · 4,1★ (963 avis), bd de l'Industrie", gamme: "Brasserie" },
      { nom: "Aux 2 Ancres", cuisine: "Bistrot / burgers / tapas · 4,5★ (352 avis), pl. Madeleine Rousseau", gamme: "Bistrot" },
      { nom: "Le Rambertois Grill", cuisine: "Turc / grillades · 4,5★ (629 avis), bd de la Libération", gamme: "Brasserie" },
      { nom: "Lulu à Table", cuisine: "Cuisine de saison · 4,5★ (267 avis), rte de Cordeyron", gamme: "Bistrot" },
    ],
    associations: [
      { nom: "La Pontoise Basket Club", activite: "Club emblématique, équipe sénior masculine en Nationale 2" },
      { nom: "Saint-Just-Saint-Rambert Football", activite: "Football amateur" },
      { nom: "Tennis Club Saint-Just-Saint-Rambert", activite: "Tennis avec courts couverts" },
      { nom: "Aviron Forez", activite: "Aviron sur le plan d'eau de Saint-Pierre" },
      { nom: "Office de tourisme Loire Forez", activite: "Activités plein air et culturelles" },
    ],
    quartiers: [
      { nom: "Centre Saint-Just", description: "Centre commerçant, école, services, ambiance plus urbaine.", prixIndicatif: "2 500 — 3 200 €/m²" },
      { nom: "Saint-Rambert", description: "Vieille ville médiévale, prieuré du XIᵉ, ruelles charmantes.", prixIndicatif: "2 600 — 3 500 €/m²" },
      { nom: "Les Bords de Loire", description: "Maisons avec vue rivière, quartier prisé, balade fluviale aux pieds.", prixIndicatif: "2 800 — 3 800 €/m²" },
    ],
    evolutionPrix: [
      { annee: 2020, prixM2: 2400 }, { annee: 2021, prixM2: 2600 }, { annee: 2022, prixM2: 2750 },
      { annee: 2023, prixM2: 2780 }, { annee: 2024, prixM2: 2790 }, { annee: 2025, prixM2: 2800 },
    ],
    videoInsta: { titre: "La Plaine du Forez : pourquoi y investir maintenant", duree: "1:50" },
    galerie: ["/photos/secteurs/saint-just-1.jpg", "/photos/secteurs/saint-just-2.jpg", "/photos/secteurs/saint-just-3.jpg", "/photos/secteurs/saint-just-4.jpg", "/photos/secteurs/saint-just-5.jpg", "/photos/secteurs/saint-just-6.jpg"],
  },
};
